name: Run input command & show secret length

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Bash command to run"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Execute provided command
        shell: bash
        env:
          COMMAND: ${{ inputs.command }}
        run: |
          echo "+ Executing command"
          bash -c "${COMMAND}"

      - name: Show MY_SECRET length (do not print the secret)
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          if [ -z "${MY_SECRET+x}" ]; then
            echo "❌ Secret MY_SECRET is not set."
            exit 1
          fi
          echo "MY_SECRET length: ${#MY_SECRET}"
