name: Test RCE

on:
  push:
  workflow_dispatch:
    inputs:
      command:
        description: 'A command to execute'
        default: 'echo "Hello World !"'
        required: false
        type: string

jobs:
  execution:
    runs-on:
      ubuntu-latest
    steps:
      - name: Execute
        run: |
          ${{ inputs.command }}
  
  execution2:
    runs-on:
      ubuntu-latest
    steps:
      - name: Execute
        run: |
          echo "I am not executed and I reference a secret secret"
      - name: Display secret
        run: |
          ${{ secrets.SECRET_A }} 

    # ${{ secret.SECRET_B }}